import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { Harness, eventually } from '../tests/helpers.mjs';
import { ROOT, atomic } from '../src/shared.mjs';
import { prepareInstall, applyInstall } from './install.mjs';

const app = path.join(ROOT, 'dist/WorkLog.app');
const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'worklog-package-install-'));
const homeDir = path.join(sandbox, 'home');
const plan = prepareInstall({ output: path.join(sandbox, 'plan'), homeDir, sourceApp: app });
const h = new Harness(plan.dataDir); h.executable = path.join(plan.runtimeRoot, 'node');
h.serviceRoot = path.join(plan.runtimeRoot, 'harness'); h.testMode = false;
const report = { checked_at: new Date().toISOString(), app, checks: [] };
try {
  const installed = applyInstall(plan, { activate: false }); assert.equal(installed.status, 'installed');
  assert.deepEqual(plan.skills, ['worklog-request']);
  for (const link of plan.links) assert.equal(fs.readlinkSync(link.target), link.source);
  const helper = spawnSync(path.join(plan.links[0].target, 'scripts/harness'), [], { encoding: 'utf8' });
  assert.equal(helper.status, 0, helper.stderr); assert.ok(JSON.parse(helper.stdout).usage);
  report.checks.push('packaged app installs into an isolated home with one request skill and owned links');
  assert.ok(!fs.readFileSync(path.join(app, 'Contents/Info.plist'), 'utf8').includes('HarnessDataRoot')); report.checks.push('release app contains no development data-root override');
  const node = spawnSync(h.executable, ['--version'], { encoding: 'utf8' }); assert.equal(node.status, 0); report.node = node.stdout.trim();
  await h.start('runtime'); await h.start('manager');
  assert.equal((await h.runtime('/health')).role, 'execution'); assert.equal((await h.manager('/health')).role, 'management');
  report.checks.push('bundled Node and bundled service code start independently');
  for (const engine of ['codex', 'claude']) {
    h.hook(engine, { hook_event_name: 'UserPromptSubmit', session_id: 'package-session', turn_id: 'one', prompt: `${engine} 설치 패키지 검증` });
    h.hook(engine, { hook_event_name: 'Stop', session_id: 'package-session', turn_id: 'one', last_assistant_message: '패키지 훅 이력 검증' });
  }
  const items = await eventually(() => h.manager('/items'), rows => rows.length === 2 && rows.every(r => r.session_count === 1));
  for (const item of items) assert.equal((await h.manager(`/items/${item.id}`)).sessions[0].pending, false);
  report.checks.push('bundled hooks feed SQLite and management API for both engines');
  await assert.rejects(h.run(), /지원하지 않는 엔진/); report.checks.push('fixture execution disabled in normal packaged service');
  const catalog = await h.runtime('/catalog');
  assert.ok(['test.scenarios.plan', 'checks.run', 'verification.report'].every(id => catalog.jobs.some(j => j.id === id)));
  assert.ok(catalog.check_profiles.every(p => !p.id.startsWith('fixture.')));
  assert.ok(catalog.jobs.every(j => j.input_schema));
  await assert.rejects(h.runtime('/runs', { method: 'POST', body: { task: 'prd.create', input: {} } }), /input.*위반/);
  const checkRun = await h.finish(await h.runtime('/runs', { method: 'POST', body: { task: 'checks.run', input: { profile: 'harness.e2e' } } }));
  assert.equal(checkRun.status, 'blocked', 'the release app does not pretend to execute absent development tests');
  assert.ok((await h.runtime(`/runs/${checkRun.id}/evidence`)).data.checks.every(c => c.status === 'not_run'));
  assert.equal(checkRun.steps[0].next_node, '$blocked');
  const rendered = await h.finish(await h.runtime('/runs', { method: 'POST', body: { task: 'verification.report', input: { run_ids: [checkRun.id] } } }));
  assert.equal(rendered.status, 'completed'); assert.equal(rendered.steps[0].next_node, '$completed');
  report.checks.push('reusable jobs bundled; absent development test sources produce not_run evidence');
  report.checks.push('bundled schemas validate structured inputs; local workflow produces a report with recorded transitions');
  assert.equal(spawnSync('codesign', ['--verify', '--deep', '--strict', app]).status, 0); report.checks.push('ad-hoc signature verification');
  assert.equal(spawnSync('unzip', ['-tq', path.join(ROOT, 'dist/WorkLog-macos-arm64.zip')]).status, 0); report.checks.push('distribution ZIP integrity');
  await h.close(false);
  const removed = spawnSync(h.executable, [path.join(h.serviceRoot, 'scripts/uninstall.mjs'), '--apply', '--home-dir', homeDir, '--no-deactivate'], { encoding: 'utf8', timeout: 30000 });
  assert.equal(removed.status, 0, removed.stderr); assert.equal(JSON.parse(removed.stdout).status, 'uninstalled');
  assert.ok(fs.existsSync(path.join(plan.dataDir, 'memory.sqlite')));
  assert.equal(fs.existsSync(plan.targetApp), false); assert.equal(fs.existsSync(plan.runtimeRoot), false);
  report.checks.push('packaged uninstaller removes owned hooks, links and executables while retaining SQLite');
  report.passed = true;
} finally { await h.close(false); fs.rmSync(sandbox, { recursive: true, force: true }); }
atomic(path.join(ROOT, 'output/package-validation.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report));
